### ISSUE TITLE
Register Miner in the Burst dAppository

### ISSUE THREAD

**Issue by ohager** [andzno1/blagominer#11]
Hi @andzno1.

First of all...thank you for that valuable contribution to the community. It seems that you are not active anymore in the Burst space, but I'd like you to list (in the name of the community) your contribution in https://burst.dappository.world/

If you are not interested, I'd like to ask for your permission to list it in the name of the community using a funding account.

**Comment by andzno1** [comment]
Hi @ohager,

thanks for contacting me. Feel free to list me on the mentioned page. You are right, I am not actively developing right now. I am still running a full node and mining Burstcoin, though.

**Comment by ohager** [comment]
> Hi @ohager,
> 
> thanks for contacting me. Feel free to list me on the mentioned page. You are right, I am not actively developing right now. I am still running a full node and mining Burstcoin, though.

If you register with your own Burst account you may receive the donations for this project. If you don't care I go ahead with a community account and using eventual donations for funding.

**Comment by ohager** [comment]
@andzno1 https://burst.dappository.world/token/11812505045748510005 - Finally, I registered it. If you want I can transfer the token to you, just send me a Burst Address under your control. Closing.
